compose:
  output_file: docker-compose.yaml
  test_output_file: docker-compose.test.yaml
  rabbitmq_ports: true

settings:
  logging_level: INFO
  server_port: 5678
  chunk_max_bytes: 1048576
  result_line_max_bytes: 1048576
  connect_timeout_seconds: 30
  io_timeout_seconds: 3600

workers:
  file_splitters: 3
  file_ingestors: 3
  filters:
    usd: 3
    q1: 3
    date: 3
  sums:
    q2: 3
    q3: 3
  aggregators:
    q2: 3
    q3: 3
  joiners:
    q2: 1
    q3: 1
  scatter_gather:
    mappers: 3
    linkers: 3
    detectors: 6
    min_intermediaries: 5

clients: 3
client_accounts:
  - client_id: 0
    accounts_file: data/datasets/client-1/LI-Small/LI-Small_accounts.csv
    transactions_file: data/datasets/client-1/LI-Small/LI-Small_Trans.csv
  - client_id: 1
    accounts_file: data/datasets/client-1/LI-Small/LI-Small_accounts.csv
    transactions_file: data/datasets/client-1/LI-Small/LI-Small_Trans.csv
  - client_id: 2
    accounts_file: data/datasets/client-1/LI-Small/LI-Small_accounts.csv
    transactions_file: data/datasets/client-1/LI-Small/LI-Small_Trans.csv
