compose:
  output_file: docker-compose.yaml
  test_output_file: docker-compose.test.yaml
  rabbitmq_ports: true

settings:
  logging_level: INFO
  server_port: 5678
  chunk_max_bytes: 1048576
  result_line_max_bytes: 1048576
  connect_timeout_seconds: 30
  io_timeout_seconds: 3600

workers:
  file_splitters: 2
  file_ingestors: 2
  filters:
    usd: 2
    q1: 2
    date: 2
  sums:
    q2: 3
    q3: 3
  aggregators:
    q2: 2
    q3: 2
  joiners:
    q2: 1
    q3: 1
  scatter_gather:
    mappers: 2
    linkers: 2
    detectors: 2
    min_intermediaries: 5
  q4:
    filters: 2
    sums: 2
    joiners: 4
    aggregators: 4
    dedupers: 2

clients: 3
client_accounts:
  - client_id: 0
    accounts_file: data/datasets/client-1/LI-Small/LI-Small_accounts.csv
    transactions_file: data/datasets/client-1/LI-Small/LI-Small_Trans.csv
  - client_id: 1
    accounts_file: data/datasets/client-1/LI-Mini/LI-Mini_accounts.csv
    transactions_file: data/datasets/client-1/LI-Mini/LI-Mini_Trans.csv
  - client_id: 2
    accounts_file: data/datasets/client-1/LI-Small/LI-Small_accounts.csv
    transactions_file: data/datasets/client-1/LI-Small/LI-Small_Trans.csv
