compose:
  output_file: docker-compose.yaml
  test_output_file: docker-compose.test.yaml
  rabbitmq_ports: true

settings:
  logging_level: INFO
  server_port: 5678
  chunk_max_bytes: 65536
  result_line_max_bytes: 1048576
  connect_timeout_seconds: 30
  io_timeout_seconds: 3600

workers:
  file_splitters: 1
  file_ingestors: 1
  filters:
    usd: 1
    q1: 1
    date: 1
  sums:
    q2: 3
    q3: 3
  aggregators:
    q2: 1
    q3: 1
  joiners:
    q2: 1
    q3: 1
  scatter_gather:
    mappers: 1
    linkers: 1
    detectors: 6
    min_intermediaries: 5

clients: 1
client_accounts:
  - client_id: 0
    accounts_file: data/datasets/client-1/LI-Small/LI-Small_accounts.csv
    transactions_file: data/datasets/client-1/LI-Small/LI-Small_Trans.csv
