compose:
  output_file: docker-compose.yaml
  test_output_file: docker-compose.test.yaml
  rabbitmq_ports: true
  rabbitmq_durable: false
  rabbitmq_publisher_confirms: false

settings:
  logging_level: INFO
  server_port: 5678
  chunk_max_bytes: 65536
  result_line_max_bytes: 1048576
  connect_timeout_seconds: 30
  io_timeout_seconds: 3600
  filter_prefetch_count: 50
  snapshot_interval: 10000

workers:
  file_splitters: 3
  file_ingestors: 6
  filters:
    usd: 6
    q1: 3
    date: 4
    q5_format: 3
    q5_usd: 3
  sums:
    q2: 4
    q3: 6
  aggregators:
    q2: 3
    q3: 3
    q5: 2
  joiners:
    q2: 1
    q3: 1
    q5: 1
  q3_barrier: 2
  q4:
    filters: 6
    sums: 4
    joiners: 8
    aggregators: 8
    dedupers: 2

clients: 2
client_accounts:
  - client_id: 0
    accounts_file: data/datasets/HI-Medium/HI-Medium_accounts.csv
    transactions_file: data/datasets/HI-Medium/HI-Medium_Trans.csv
  - client_id: 1
    accounts_file: data/datasets/HI-Medium/HI-Medium_accounts.csv
    transactions_file: data/datasets/HI-Medium/HI-Medium_Trans.csv
