#!/usr/bin/env python3
"""Full end-to-end pipeline test for the whole system (Q1-Q5).

Unlike the old smoke test (which only grep'd the log for a few success
patterns), this:

1. Kills every leftover TP container (main + test compose projects).
2. Brings up the full test stack (docker-compose.test.yaml, already generated by
   the Makefile from config/test-config.yaml) and streams its logs through
   pretty_logs.py so the run is still nice to watch.
3. Samples ``docker stats`` while it runs to capture peak CPU/RAM (and spikes).
4. After the clients finish, validates the real output of EVERY query for EVERY
   client against the precomputed reference (data/datasets/<DATASET>/expected_results/).
5. Prints a metrics footer as the LAST entries in the log: per-query PASS/FAIL +
   elapsed, total wall time, container count, peak CPU/RAM + worst offenders.
6. Tears the whole stack down (unless KEEP_CONTAINERS is set).

Configuration is read from the environment (set by the Makefile):
  DATASET, LOG_COLOR, TEST_PROJECT, MAIN_PROJECT, TEST_COMPOSE_FILE,
  TEST_CLIENT_WAIT_TIMEOUT, KEEP_CONTAINERS, DATASET_ROOT, METRICS_INTERVAL.
"""
import os
import re
import signal
import subprocess
import sys
import tempfile
import threading
import time
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import reference_results as ref

ROOT = Path(__file__).resolve().parents[1]
PRETTY_LOGS = ROOT / "scripts" / "pretty_logs.py"

DATASET = os.environ.get("DATASET", "LI-Small")
DATASET_ROOT = os.environ.get("DATASET_ROOT", "data/datasets")
LOG_COLOR = os.environ.get("LOG_COLOR", "always")
TEST_PROJECT = os.environ.get("TEST_PROJECT", "distribuidos-test")
MAIN_PROJECT = os.environ.get("MAIN_PROJECT", Path.cwd().name.lower())
COMPOSE_FILE = os.environ.get("TEST_COMPOSE_FILE", "docker-compose.test.yaml")
WAIT_TIMEOUT = os.environ.get("TEST_CLIENT_WAIT_TIMEOUT", "600s")
KEEP_CONTAINERS = bool(os.environ.get("KEEP_CONTAINERS", "").strip())
METRICS_INTERVAL = float(os.environ.get("METRICS_INTERVAL", "2"))

QUERIES = list(ref.QUERIES)
# gateway_eof line prefixes per query (gateway logs prefix or "Q1"); see
# src/gateway/gateway.py _run_result_consumer.
EOF_PATTERNS = {
    "q1": "gateway_eof | prefix=Q1 |",
    "q2": "gateway_eof | prefix=Q2| |",
    "q3": "gateway_eof | prefix=Q3| |",
    "q4": "gateway_eof | prefix=Q4| |",
    "q5": "gateway_eof | prefix=Q5| |",
}
_CLIENT_ID_RE = re.compile(r"client_id=(\d+)")

BAR = "=" * 60


def compose(*args):
    return ["docker", "compose", "-p", TEST_PROJECT, "-f", COMPOSE_FILE, *args]


def run(cmd, **kwargs):
    return subprocess.run(cmd, **kwargs)


def quiet(cmd):
    return subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


# --------------------------------------------------------------------------- #
# cleanup / teardown
# --------------------------------------------------------------------------- #
def kill_project(project):
    """Force-remove containers and networks for a compose project by label."""
    label = f"label=com.docker.compose.project={project}"
    ids = subprocess.run(
        ["docker", "ps", "-aq", "--filter", label],
        capture_output=True, text=True,
    ).stdout.split()
    if ids:
        quiet(["docker", "rm", "-f", *ids])
    nets = subprocess.run(
        ["docker", "network", "ls", "-q", "--filter", label],
        capture_output=True, text=True,
    ).stdout.split()
    if nets:
        quiet(["docker", "network", "rm", *nets])


def teardown():
    quiet(compose("down", "--volumes", "--remove-orphans"))
    kill_project(TEST_PROJECT)


def cleanup_all():
    print("Killing leftover TP containers (main + test projects)...")
    teardown()
    kill_project(MAIN_PROJECT)
    out = Path("data/output")
    out.mkdir(parents=True, exist_ok=True)
    for f in out.glob("results_q*.csv"):
        f.unlink()


# --------------------------------------------------------------------------- #
# metrics sampler
# --------------------------------------------------------------------------- #
_MEM_UNITS = {
    "B": 1.0 / (1024 * 1024),
    "KB": 1.0 / 1024, "KIB": 1.0 / 1024,
    "MB": 1.0, "MIB": 1.0,
    "GB": 1024.0, "GIB": 1024.0,
    "TB": 1024.0 * 1024, "TIB": 1024.0 * 1024,
}


def _mem_to_mib(text):
    m = re.match(r"\s*([0-9.]+)\s*([A-Za-z]+)", text)
    if not m:
        return 0.0
    return float(m.group(1)) * _MEM_UNITS.get(m.group(2).upper(), 1.0)


class MetricsSampler(threading.Thread):
    def __init__(self, project, interval):
        super().__init__(daemon=True)
        self._project = project + "-"
        self._interval = interval
        self._stopev = threading.Event()
        self.peak_cpu_by_container = defaultdict(float)
        self.peak_mem_by_container = defaultdict(float)
        self.peak_total_cpu = 0.0
        self.peak_total_mem = 0.0
        self.containers = set()

    def stop(self):
        self._stopev.set()

    def run(self):
        fmt = "{{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}"
        while not self._stopev.is_set():
            proc = subprocess.run(
                ["docker", "stats", "--no-stream", "--format", fmt],
                capture_output=True, text=True,
            )
            total_cpu = 0.0
            total_mem = 0.0
            for line in proc.stdout.splitlines():
                parts = line.split("\t")
                if len(parts) != 3:
                    continue
                name, cpu_s, mem_s = parts
                if not name.startswith(self._project):
                    continue
                try:
                    cpu = float(cpu_s.replace("%", "").strip())
                except ValueError:
                    continue
                mem = _mem_to_mib(mem_s.split("/")[0])
                self.containers.add(name)
                total_cpu += cpu
                total_mem += mem
                self.peak_cpu_by_container[name] = max(
                    self.peak_cpu_by_container[name], cpu)
                self.peak_mem_by_container[name] = max(
                    self.peak_mem_by_container[name], mem)
            self.peak_total_cpu = max(self.peak_total_cpu, total_cpu)
            self.peak_total_mem = max(self.peak_total_mem, total_mem)
            self._stopev.wait(self._interval)


# --------------------------------------------------------------------------- #
# per-query timing watcher (tails the tee'd raw log)
# --------------------------------------------------------------------------- #
class TimingWatcher(threading.Thread):
    def __init__(self, log_file, num_clients, start):
        super().__init__(daemon=True)
        self._log_file = log_file
        self._num_clients = num_clients
        self._start = start
        self._stopev = threading.Event()
        self.done_at = {}
        self._seen = {q: set() for q in QUERIES}

    def stop(self):
        self._stopev.set()

    def _scan(self, text):
        for line in text.splitlines():
            for q, pat in EOF_PATTERNS.items():
                if q in self.done_at or pat not in line:
                    continue
                m = _CLIENT_ID_RE.search(line)
                self._seen[q].add(m.group(1) if m else line)
                if len(self._seen[q]) >= self._num_clients:
                    self.done_at[q] = time.monotonic() - self._start

    def run(self):
        pos = 0
        while not self._stopev.is_set():
            try:
                with open(self._log_file, "r", errors="replace") as f:
                    f.seek(pos)
                    chunk = f.read()
                    pos = f.tell()
            except FileNotFoundError:
                chunk = ""
            if chunk:
                self._scan(chunk)
            self._stopev.wait(0.5)
        # final pass to catch anything written just before stop
        try:
            with open(self._log_file, "r", errors="replace") as f:
                f.seek(pos)
                self._scan(f.read())
        except FileNotFoundError:
            pass


# --------------------------------------------------------------------------- #
# validation
# --------------------------------------------------------------------------- #
def ensure_reference():
    missing = [q for q in QUERIES if not ref.expected_path(Path(DATASET_ROOT) / DATASET, q).exists()]
    if not missing:
        return
    print(f"Reference results missing for {missing}; precomputing for {DATASET}...")
    run([sys.executable, str(ROOT / "scripts" / "precompute_expected.py"),
         "--dataset", DATASET, "--dataset-root", DATASET_ROOT])


def validate_all():
    results = {}
    dataset_dir = f"{DATASET_ROOT}/{DATASET}"
    trans = f"{DATASET}_Trans.csv"
    for q in QUERIES:
        env = dict(os.environ)
        env[f"{q.upper()}_DATASET_DIR"] = dataset_dir
        env[f"{q.upper()}_DATASET_TRANS"] = trans
        proc = run([sys.executable, str(ROOT / "scripts" / f"validate_{q}_output.py")], env=env)
        results[q] = proc.returncode == 0
    return results


# --------------------------------------------------------------------------- #
# summary footer
# --------------------------------------------------------------------------- #
def print_summary(results, timings, sampler, wall, timed_out, num_clients):
    print()
    print(BAR)
    print("FULL PIPELINE TEST SUMMARY")
    print(BAR)
    print(f"Dataset: {DATASET}   Clients: {num_clients}")
    print()
    print(f"{'Query':<8}{'Result':<10}{'Pipeline time':<16}")
    for q in QUERIES:
        mark = "✓ PASS" if results.get(q) else "✗ FAIL"
        t = timings.get(q)
        t_str = f"{t:.1f}s" if t is not None else "—"
        print(f"{q.upper():<8}{mark:<10}{t_str:<16}")
    print()
    print(f"Total wall time : {wall:.1f}s")
    if timed_out:
        print("WARNING: client wait timed out before all clients finished")
    print(f"Containers      : {len(sampler.containers)}")
    print(f"Peak CPU (total): {sampler.peak_total_cpu:.1f}%")
    print(f"Peak RAM (total): {sampler.peak_total_mem:.0f} MiB "
          f"({sampler.peak_total_mem / 1024:.2f} GiB)")

    def top(d, n=3):
        return sorted(d.items(), key=lambda kv: kv[1], reverse=True)[:n]

    if sampler.peak_cpu_by_container:
        print("Top CPU spikes  : " + ", ".join(
            f"{name.replace(TEST_PROJECT + '-', '')}={v:.0f}%"
            for name, v in top(sampler.peak_cpu_by_container)))
    if sampler.peak_mem_by_container:
        print("Top RAM spikes  : " + ", ".join(
            f"{name.replace(TEST_PROJECT + '-', '')}={v:.0f}MiB"
            for name, v in top(sampler.peak_mem_by_container)))
    print(BAR)
    overall = all(results.values()) and not timed_out
    if overall:
        print("✓✓✓ FULL PIPELINE TEST PASSED ✓✓✓")
    else:
        print("✗✗✗ FULL PIPELINE TEST FAILED ✗✗✗")
    print(BAR)
    return overall


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #
def main():
    log_fd, log_path = tempfile.mkstemp(prefix=f"{TEST_PROJECT}.", suffix=".log")
    os.close(log_fd)
    print(f"test_log_file={log_path}")

    cleanup_all()
    ensure_reference()

    log_proc = None
    sampler = MetricsSampler(TEST_PROJECT, METRICS_INTERVAL)
    watcher = None
    timed_out = False
    start = time.monotonic()

    try:
        print(f"Building and starting full test stack ({DATASET})...")
        if run(compose("up", "--build", "--remove-orphans", "--detach")).returncode != 0:
            print("ERROR: docker compose up failed", file=sys.stderr)
            return 2

        services = subprocess.run(
            compose("config", "--services"), capture_output=True, text=True).stdout.split()
        clients = [s for s in services if s.startswith("client_")]
        if not clients:
            print("ERROR: no client services found", file=sys.stderr)
            return 2
        num_clients = len(clients)

        sampler.start()
        watcher = TimingWatcher(log_path, num_clients, start)
        watcher.start()

        # stream logs -> pretty_logs (tee raw lines for the watcher/validation)
        log_cmd = (
            f'docker compose -p {TEST_PROJECT} -f {COMPOSE_FILE} '
            f'logs --follow --timestamps --no-color | '
            f'{sys.executable} {PRETTY_LOGS} --color {LOG_COLOR} --tee-file {log_path}'
        )
        log_proc = subprocess.Popen(log_cmd, shell=True, start_new_session=True)

        print(f"Waiting for {num_clients} client(s) to finish (timeout {WAIT_TIMEOUT})...")
        try:
            run(compose("wait", *clients), timeout=_seconds(WAIT_TIMEOUT),
                stdout=subprocess.DEVNULL)
        except subprocess.TimeoutExpired:
            timed_out = True
            print("WARNING: timed out waiting for clients", file=sys.stderr)

        # give the gateway/clients a moment to flush final logs + output files
        time.sleep(3)
    finally:
        sampler.stop()
        if watcher is not None:
            watcher.stop()
            watcher.join(timeout=5)
        sampler.join(timeout=5)
        if log_proc is not None:
            _kill_pipeline(log_proc)

    wall = time.monotonic() - start
    print()
    results = validate_all()
    overall = print_summary(
        results, (watcher.done_at if watcher else {}), sampler, wall,
        timed_out, num_clients)

    if KEEP_CONTAINERS:
        print(f"KEEP_CONTAINERS set — leaving stack up. Tear down with:\n"
              f"  docker compose -p {TEST_PROJECT} -f {COMPOSE_FILE} down --volumes --remove-orphans")
    else:
        teardown()

    try:
        os.unlink(log_path)
    except OSError:
        pass
    return 0 if overall else 1


def _seconds(value):
    value = value.strip().lower()
    if value.endswith("s"):
        value = value[:-1]
    return float(value)


def _kill_pipeline(proc):
    try:
        os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
    except (ProcessLookupError, PermissionError):
        pass
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        try:
            os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
        except (ProcessLookupError, PermissionError):
            pass


if __name__ == "__main__":
    sys.exit(main())
