#!/usr/bin/env python3
"""Validate Q1 output (USD transactions paying less than 50).

Compares every ``results_q1_*.csv`` against the precomputed reference
(``<dataset>/expected_results/q1.csv``, regenerated by precompute_expected.py),
falling back to computing it from the dataset when the reference is absent.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import reference_results as ref

DATASET_DIR = os.environ.get("Q1_DATASET_DIR", "data/datasets/LI-Mini")
DATASET_TRANS = os.environ.get("Q1_DATASET_TRANS", "LI-Mini_Trans.csv")


if __name__ == "__main__":
    print("=" * 60)
    print("Q1 FLOW VALIDATION")
    print("=" * 60)
    success = ref.validate_query("q1", DATASET_DIR, DATASET_TRANS)
    print("=" * 60)
    if success:
        print("✓✓✓ Q1 TEST PASSED ✓✓✓")
        sys.exit(0)
    print("✗✗✗ Q1 TEST FAILED ✗✗✗")
    sys.exit(1)
